github: [ahmeterdgn] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: ahmeterdgn # Replace with a single Patreon username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
